version: '3.8'

services:
  fedrl:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./plots:/app/plots
    environment:
      - SDL_VIDEODRIVER=dummy
      - DISPLAY=:0
    cpus: '16'
    mem_limit: 32g
